apiVersion: v1
kind: Service
metadata:
  name: api-loadbalancer-service
spec:
  selector:
    pod: api-deployment
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32500
  type: NodePort
