apiVersion: v1
kind: Service
metadata:
  name: flower-cluster-ip-service
spec:
  selector:
    pod: flower-deployment
  ports:
    - port: 5555
      targetPort: 5555
      nodePort: 32600
  type: NodePort
